// let marks=35;
// if(marks<35){
//     console.log("Failed in exam");
// }
// else{
//     console.log("Passed in exam");
//}
//  let day =prompt("Enter the day number");
//  if(day == 1){
//     console.log("Monday");
//  }
//  else if(day == 2){
//     console.log("Tuesday");
//  }
//  else if(day == 3){
//     console.log("Wednesday");
//  }
//  else{
//     console.log("Invalid");
//  }

//  let day =Number(prompt("Enter day number"));
//  console.log(typeof(day));
//  switch(day){
//  case 1:
//     console.log("Monday");
//     break;
// case 2:
//     console.log("Tuesday");
//     break;
// case 3:
//     console.log("Wednesday");
//     break;
// default:
//     console.log("Invalid");
//     break;
//  }

let a = 120;
let b =30;
let c = 10;
if(a > b){
    console.log("a is greater"+a);
}
else if(a < b){
    console.log("b is greater"+b);
}
else {
    console.log("c is greater"+c);
}

